version: '3'

volumes:
  sentry_pgdb:
  sentry_redis:

networks:
  global:
    external: true

services:
  redis:
    image: redis
    container_name: redis.monitor.docker
    restart: unless-stopped
    volumes:
    - sentry_redis:/data
    networks:
    - global

  postgres:
    image: postgres
    container_name: postgres.monitor.docker
    restart: unless-stopped
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DB: sentry
    volumes:
    - sentry_pgdb:/var/lib/postgresql/data
    networks:
    - global

  sentry:
    image: sentry
    container_name: sentry.monitor.docker
    restart: unless-stopped
    links:
    - redis
    - postgres
    ports:
    - 127.0.0.1:9000:9000
    env_file:
    - ./docker/default.config.env
    networks:
    - global

  cron:
    image: sentry
    container_name: cron.monitor.docker
    restart: unless-stopped
    links:
    - redis
    - postgres
    command: "sentry run cron"
    env_file:
    - ./docker/default.config.env
    networks:
    - global

  worker:
    image: sentry
    container_name: worker.monitor.docker
    restart: unless-stopped
    links:
    - redis
    - postgres
    command: "sentry run worker"
    env_file:
    - ./docker/default.config.env
    networks:
    - global
